###

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hearly-backend
  labels:
    app: hearly-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hearly-backend
  template:
    metadata:
      labels:
        app: hearly-backend
    spec:
      containers:
        - name: hearly-backend
          image: us-west1-docker.pkg.dev/ccbd-25-sergiomancini/hearly-repo/hearly-backend:v14
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: AWS_REGION
              value: "eu-west-2"
            - name: S3_BUCKET_NAME
              value: "cc-bucket-audio"
            - name: S3_OUTPUT_BUCKET
              value: "cc-transcribe-output"
            - name: S3_SUMMARIES_BUCKET
              value: "cc-summaries-bucket"
            - name: LAMBDA_FUNCTION_NAME
              value: "lambda-audio-transcribe"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: hearly-aws-credentials
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: hearly-aws-credentials
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_COGNITO_APP_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: hearly-aws-credentials
                  key: AWS_COGNITO_APP_CLIENT_ID
            - name: AWS_COGNITO_USER_POOL_ID
              valueFrom:
                secretKeyRef:
                  name: hearly-aws-credentials
                  key: AWS_COGNITO_USER_POOL_ID
            - name: AWS_COGNITO_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: hearly-aws-credentials
                  key: AWS_COGNITO_CLIENT_SECRET
            - name: AZURE_OAI_KEY
              valueFrom:
                secretKeyRef:
                  name: hearly-aws-credentials
                  key: AZURE_OAI_KEY
            - name: AZURE_OAI_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: hearly-aws-credentials
                  key: AZURE_OAI_ENDPOINT
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: hearly-backend-service
spec:
  selector:
    app: hearly-backend
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
